### ISSUE TITLE
no esp32 cam demo?

### ISSUE THREAD

**Issue by lenghonglin** [m5stack/M5Stack#106]

**Comment by sakabin** [comment]
demo use esp-idf, you can see,  https://github.com/m5stack/esp32-cam-demo

**Comment by lenghonglin** [comment]
@sakabin  i see this demo，but i want to develop with arduino, how can i do?

**Comment by sakabin** [comment]
sorry, no support now

**Comment by lenghonglin** [comment]
tks,hope support soon

**Comment by zhouyangyale** [comment]
now，you can see，https://github.com/m5stack/Applications-cam
