### ISSUE TITLE
Load a smooth font from SPIFFS

### ISSUE THREAD

**Issue by vvs551** [m5stack/M5Stack#112]
How to load a smooth font *.vlw from SPIFFS with Display library?
Like TFT_eSPI void loadFont

**Comment by komikoni** [comment]
Supplementary explanation
https://github.com/komikoni/M5Stack/commit/6b47f2e79d150588728537d61641cd9e1ea5ed88

Below is a copy from etft's library.
src/utility/Smooth_font.cpp
src/utility/Smooth_font.h
