### ISSUE TITLE
Pipes leave lines behind them in flappy bird example

### ISSUE THREAD

**Issue by joeybab3** [m5stack/M5Stack#119]
When playing the flappy bird example, the pipes leave lines behind them as shown below:

![img_5592](https://user-images.githubusercontent.com/2829457/51815139-e4fed480-2273-11e9-94fb-473a9a89d531.JPG)

**Comment by psx88** [comment]
@joeybab3 Same error on my device. Also the sound seems to be too high pitched and sounds extremely crackling (Tested different sketches and sound files/formats). Getting the grey and the fire version next week. If this issue isn't affecting the next devices, the first one (black edition) is going back to the vendor.

**Comment by sakabin** [comment]
Hello, I test is woks well, do you change other things?
![1449937251](https://user-images.githubusercontent.com/24584225/53715073-a1f3da80-3e8b-11e9-9fec-106794b6aabf.jpg)

**Comment by joeybab3** [comment]
No it’s straight off of GitHub

**Comment by sakabin** [comment]
Please try update esp32-arduino and m5stack lib, i test it in different core, they are all woks well
