### ISSUE TITLE
M5.Lcd.drawJpgFile doesn't work. ( after #122 Update to TFT_eSPI )

### ISSUE THREAD

**Issue by lovyan03** [m5stack/M5Stack#131]
M5.Lcd.drawJpgFile doesn't work.
 after #122 Update to TFT_eSPI .

**Comment by zhouyangyale** [comment]
Yes, I check it。

**Comment by lovyan03** [comment]
I fix it now. #145

**Comment by lovyan03** [comment]
I found a better way, so I'll close it

**Comment by lovyan03** [comment]
I made a pull request again. #146
