### ISSUE TITLE
Issue when running http server

### ISSUE THREAD

**Issue by Herwey** [m5stack/M5Stack#133]
Hi
When I run the demo about http jpg_stream, on the terminal, it showed :
E (22410) esp_jpg_decode: JPG Decompression Failed! Data format error
E (22410) example:http_jpg: fmt2rgb888 failed
W (22410) httpd_uri: httpd_uri: uri handler execution failed
Why is it? It happenned after the demo had been running for a while.
Thanks in advance

**Comment by zhouyangyale** [comment]
Can you tell me the address of this demo?

**Comment by Herwey** [comment]
m5stack-cam-psram/main

**Comment by Zontex** [comment]
Hello, is this issue still relevant? it should work with the new libraries and code. closing for now, if relevant feel free to open.
