### ISSUE TITLE
How to support for PlatformIO?

### ISSUE THREAD

**Issue by sczh01** [m5stack/M5Stack#14]
Hi Team,

Would we support PlatformIO?

thanks
tony

**Comment by imxieyi** [comment]
I think you can refer to the guide on [arduino-esp32](https://github.com/espressif/arduino-esp32)

**Comment by avaldebe** [comment]
Maybe I'm misunderstanding the question.

The m5stack is already supported by PlatformIO. I'm running PlatformIO Atom plugin (core 3.5.0a9). Just started a new project for the `m5stack-core-esp32` from the IDE and got the following entry to my `platformio.ini`. 

```
[env:m5stack-core-esp32]
platform = espressif32
board = m5stack-core-esp32
framework = arduino
```
After that all I needed to do was to put this library on the `lib/` directory, and could compile the examples

**Comment by sczh01** [comment]
.thanks it's my request in platformio.
