### ISSUE TITLE
Click sound when entering / exiting sleep

### ISSUE THREAD

**Issue by jtgrassie** [m5stack/M5Stack#159]
For reference, there is a forum thread [here](http://forum.m5stack.com/topic/61/noise-on-speaker) on this issue, but none of the "solutions" work (at least not on an M5 Fire).

The issue seems to be related to the display being switched on/off in the power sleep methods.

**Comment by MateuszZiolek** [comment]
so old but let me reply.

in Python
`dac0 = machine.DAC(25)
dac0.write(0)`

**Comment by Zontex** [comment]
seems like you got an answer, I tested seems to be working. if still relevant let me know. closing for now.
