### ISSUE TITLE
Pinout on a image for 1 and 3 seem be wrong.

### ISSUE THREAD

**Issue by asukiaaa** [m5stack/M5Stack#174]
I think that 1 is TX0 and 3 si RX0 on https://github.com/m5stack/M5Stack/blob/master/docs/M-BUS.jpg
I wanted to update the picture but I cannot find updated one.
Could you replace it?
Thank you.

**Comment by EeeeBin** [comment]
Fixed, see https://github.com/m5stack/M5Stack/commit/ed423d922755dfd3df99fe70c57bf3cba1801347

**Comment by asukiaaa** [comment]
Thank you for updating.
