### ISSUE TITLE
fatal error: rom/tjpgd.h: No such file or directory

### ISSUE THREAD

**Issue by GitHub-Hugl** [m5stack/M5Stack#183]
Arduino:1.8.9 (Windows 10), 开发板："NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Enabled, 4M (no SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

构建选项已变更，全部重新构建
C:\Users\Administrator\Documents\Arduino\libraries\M5Stack-master\src\M5Display.cpp:198:23: fatal error: rom/tjpgd.h: No such file or directory

 #include "rom/tjpgd.h"

                       ^

compilation terminated.

exit status 1
为开发板 NodeMCU 1.0 (ESP-12E Module) 编译时出错。

**Comment by EeeeBin** [comment]
ESP-12E Module is a esp8266, not m5stack core......
