### ISSUE TITLE
Warning: Compiler 'warning' that is fatal

### ISSUE THREAD

**Issue by plainpylut** [m5stack/M5Stack#185]
qrcode.c, line 853, the following code always evaluates to false:

bool qrcode_getModule(QRCode *qrcode, uint8_t x, uint8_t y) {
  if (x < 0 || x >= qrcode->size || y < 0 || y >= qrcode->size) {
    return false;
  }
  uint32_t offset = y * qrcode->size + x;
  return (qrcode->modules[offset >> 3] & (1 << (7 - (offset & 0x07)))) != 0;
}

uint8_t is an unsigned 8 bit integer and can NEVER contain a value less than zero!

This statement causes a fatal compile error with warnings "all" turned on.

**Comment by EeeeBin** [comment]
Fixed https://github.com/m5stack/M5Stack/commit/c7f7c0d791f1485e031e8366a6af0f5a2503fe67
