### ISSUE TITLE
MPU6886 data is not updated on M5Stack Gray

### ISSUE THREAD

**Issue by WindVoiceVox** [m5stack/M5Stack#190]
I tried with the source code below on M5Stack Gray.
The compilation is successful and it works, but the sensor information is not updated.

#include <M5Stack.h>
#include "utility/MPU6886.h"

MPU6886 IMU;

void setup() {
  // put your setup code here, to run once:
  int re;

  M5.begin();

  M5.Lcd.setBrightness(100);
  M5.Lcd.setTextSize(2);
  M5.Lcd.setTextColor(WHITE);

  re = IMU.Init();
}

float ax, ay, az;
float gx, gy, gz;
float t;

void loop() {
  // put your main code here, to run repeatedly:
  IMU.getAccelData(&ax, &ay, &az);
  IMU.getGyroData(&gx, &gy, &gz);
  IMU.getTempData(&t);

  M5.Lcd.fillScreen(BLACK);
  M5.Lcd.setCursor(0, 10);

  M5.Lcd.printf("Acc\n%.2f, %.2f, %.2f\nGyr\n%.2f, %.2f, %.2f\nTmp\n%.2f", ax, ay, az, gx, gy, gz, t);
  delay(100);
}

**Comment by EeeeBin** [comment]
Try test this example https://github.com/m5stack/M5Stack/blob/master/examples/Basics/IMU/IMU.ino

**Comment by WindVoiceVox** [comment]
Thanks, it works !
