### ISSUE TITLE
ENOMEM when making a http request

### ISSUE THREAD

**Issue by DonJayamanne** [m5stack/M5Stack#193]
Got the M5Stack grey (4MB of FLASH), and it's failing with an ENOMEM error when making an http request (micropython)

Itsa simple program uploaded using UIFlow.
Fails as soon as the http request is made using urequests

**Comment by EeeeBin** [comment]
ESP32 memory not enough to got all http request
Pls try got some web page with low content

**Comment by DonJayamanne** [comment]
Doesn't the M5Stack have 4MB?

**Comment by DonJayamanne** [comment]
I take that back, you are right. I was a few KB off...lol, hit a limit there.
Thanks and apologies

**Comment by DonJayamanne** [comment]
Sorry, I take that back, i was swallowing the exceptions.

**Comment by EeeeBin** [comment]
Sorry, I test http request got 1KB file successful (1.4.2),  could not reply this problem
Can you provide a more detailed log?
And this is arduino repositories, so this issue may be better open in here --> https://github.com/m5stack/UiFlow-Bug-Report/issues
