### ISSUE TITLE
Bluetooth Source Example

### ISSUE THREAD

**Issue by ripper121** [m5stack/M5Stack#196]
Hi :),
would it be possible to get an example of how to use the Bluetooth Source?
I like to send MP3 from the SD Card via Bluetooth  to an Bluetooth Speaker.

**Comment by Zontex** [comment]
> Hi :),
> would it be possible to get an example of how to use the Bluetooth Source?
> I like to send MP3 from the SD Card via Bluetooth to an Bluetooth Speaker.

Hello, Currently we don't support such examples but I might look at it to see what can be possibly done. you mentioning transfer file by bluetooth from the M5Stack device (SD Card) to bluetooth speaker, every bluetooth speaker is different and some might support it and some might not, need to check based on the version of the device you are having which has nothing to do with the M5Stack device itself. by theory, the M5Stack have all the required bluetooth capability so this should be possible.
