### ISSUE TITLE
M5Stack Stereo Web Radio with enclosure

### ISSUE THREAD

**Issue by nakedninja-design** [m5stack/M5Stack#199]
Hi,

I developed a stereo web radio for the M5Stack with software, audio board, 3d printed enclosure and documentation.
You can find it here: [https://github.com/nakedninja-design/M5Stack-Web-Radio](https://github.com/nakedninja-design/M5Stack-Web-Radio)

**Comment by Zontex** [comment]
Thank you for your contribution, much appreciated! feel free to share it at forum.m5stack.com, this place is mostly for issues related to the M5Stack software, closing for now.
