### ISSUE TITLE
(!IMPORTANT! but not this repository)forum site suspended

### ISSUE THREAD

**Issue by sysdl132** [m5stack/M5Stack#216]
![图片](https://user-images.githubusercontent.com/54708046/79529015-20b2d380-809e-11ea-8455-6ef129f61b78.png)
image1

The forum has been blocked on msedge(image1) and 8 more browsers.

[maybe you can reopen it on discourse(recommended)](https://discourse.org)

**Comment by sysdl132** [comment]
If I click on "continue",(please see the image below this line)
![图片](https://user-images.githubusercontent.com/54708046/79529709-f2ce8e80-809f-11ea-8f47-01a41666e0df.png)

**Comment by sysdl132** [comment]
Data of my browser:
msedge on chromium(80)
chrome(80)
firefox(74)
nwjs(chromium 79)
(4 more)
OS:windows 10

**Comment by EeeeBin** [comment]
Thanks for your reminder，we will find a way to solve this problem

**Comment by sysdl132** [comment]
I think the forum is can be normally visited now.Thanks for your support.

**Comment by sysdl132** [comment]
You can also open your sub forum at discourse.
[discourse website](https://discourse.org)
Your nodebb forum here:
![image](https://user-images.githubusercontent.com/54708046/80710785-e592b480-8b21-11ea-9d0c-7825700d43f1.png)
discourse meta:
![image](https://user-images.githubusercontent.com/54708046/80710921-1a067080-8b22-11ea-817b-998339e42dea.png)

**Comment by sysdl132** [comment]
https://meta.discourse.org/t/how-to-set-up-a-discourse-forum-for-production-use-yunohost/148222?u=sysdl132
