### ISSUE TITLE
M5Stack API hotlink on readme.md (english) leads to 404 - Not found 

### ISSUE THREAD

**Issue by zhenwei2972** [m5stack/M5Stack#220]
Please link to correct API link, link seems to be broken, should it instead direct to https://docs.makerfactory.io/m5stack/api ?

**Comment by Glastis** [comment]
Looks it moved from 
https://docs.m5stack.com/#/en/api 
to 
https://docs.m5stack.com/#/en/arduino/arduino_api

**Comment by zhenwei2972** [comment]
This should be updated to reflect the correct link, it is still very hard to locate the correct link

**Comment by Gitshaoxiang** [comment]
ok , thank you feedback.  we will contact our agent ,  tell them fix this link.
