### ISSUE TITLE
Add snake game in the examples for the Gameboy face?

### ISSUE THREAD

**Issue by ostaquet** [m5stack/M5Stack#223]
Hi,
If you want, you can enclose my code in the example for the Faces. I didn't find any playable game developed for the Faces. You can add mine (if you want): https://github.com/ostaquet/M5Snake
KR,
Olivier

**Comment by EeeeBin** [comment]
Sure, 
This example is cool and I am very happy to be able to increase the face example
Example has been added here https://github.com/m5stack/M5Stack/commit/955744d284179daea4d981175a091302e8e27851
