### ISSUE TITLE
illegal characters in M5Stack.h

### ISSUE THREAD

**Issue by sglux** [m5stack/M5Stack#230]
In M5Stack/src/M5Stack.h line 172 there are some strange quotes the code inspection of platformio mongers about.

Instead of
172 `    #error “This library only supports boards with ESP32 processor.”`
I recommend
172 `    #error "This library only supports boards with ESP32 processor."`

**Comment by Gitshaoxiang** [comment]
ok....thank feedback we will change it in the next version.
