### ISSUE TITLE
 M5Stack/examples/Unit/GPS_AT6558/FullExample/FullExample.ino says no GPS data check wiring.

### ISSUE THREAD

**Issue by ShotokuTech** [m5stack/M5Stack#234]
I can successfully get GPS data using UIFlow for my M5Stack AT6558 GPS Unit. But it is using TX21, RX22. See here: https://youtu.be/wdxeVSlC8Zw?t=525

How and where do I modify code to get FullExample.ino past "No GPS data check wiring." 

   This sample code demonstrates the normal use of a TinyGPS++ (TinyGPSPlus) object.
   It requires the use of SoftwareSerial, and assumes that you have a
   4800-baud serial GPS device hooked up on pins 4(rx) and 3(tx).

Do I adjust it here in HardwareSerial.cpp?:
#ifndef RX2
#define RX2 16
#endif

#ifndef TX2
#define TX2 17
#endif

**Comment by EeeeBin** [comment]
Just need update 
**ss.begin(GPSBaud)**
 to
 **ss.begin(GPSBaud, SERIAL_8N1, RX_PIN, TX_PIn)**

**Comment by ShotokuTech** [comment]
Thanks!
