### ISSUE TITLE
M5paper deep sleep

### ISSUE THREAD

**Issue by openmotion** [m5stack/M5Stack#238]
hello
i have problem with esp_deep_sleep_start
when the m5paper is connected with usb in my computer the deep sleep is ok, the deep sleep start and wake
but when the m5paper use the internal lipo it don't wake up 
what is the problem ?
thanks

**Comment by felmue** [comment]
Hello @openmotion 

if you look into `M5.begin()` you'll see `enableMainPower();` being called. This is GPIO2 which keeps the MOSFET open. When ESP32 goes into deep sleep by default GPIOs do not keep their state (to save energy) which in this case cuts the power to the ESP32. You'll need to make sure GPIO2 stays powered and keeps its state during deep sleep to avoid power being cut off.

BTW: this issue should be reported in the [M5Paper github repository](https://github.com/m5stack/M5EPD).

Thanks
Felix

**Comment by openmotion** [comment]
hello
thanks for your response, how to make sure GPIO2 stays powered ?
thanks

**Comment by felmue** [comment]
Hello @openmotion 

on M5CoreInk (which has a similar architecture) below lines work (note: untested on M5Paper):
```
gpio_hold_en(M5EPD_MAIN_PWR_PIN);
gpio_deep_sleep_hold_en();
esp_deep_sleep_start();
```
Thanks
Felix

**Comment by openmotion** [comment]
thanks @felmue 
i have this error
`/Users/xxx/Documents/Arduino/sketch_jan20a/sketch_jan20a.ino: In function 'void CreateRequest()':
sketch_jan20a:128:41: error: invalid conversion from 'int' to 'gpio_num_t' [-fpermissive]
          gpio_hold_en(M5EPD_MAIN_PWR_PIN);
                                         ^
In file included from /Users/xxx/Library/Arduino15/packages/m5stack/hardware/esp32/1.0.7/tools/sdk/include/esp32/esp_sleep.h:19:0,
                 from /Users/xxx/Library/Arduino15/packages/m5stack/hardware/esp32/1.0.7/tools/sdk/include/esp32/esp_system.h:21,
                 from /Users/xxx/Library/Arduino15/packages/m5stack/hardware/esp32/1.0.7/tools/sdk/include/freertos/freertos/portable.h:126,
                 from /Users/xxx/Library/Arduino15/packages/m5stack/hardware/esp32/1.0.7/tools/sdk/include/freertos/freertos/FreeRTOS.h:105,
                 from /Users/xxx/Library/Arduino15/packages/m5stack/hardware/esp32/1.0.7/cores/esp32/Arduino.h:32,
                 from sketch/sketch_jan20a.ino.cpp:1:
/Users/xxx/Library/Arduino15/packages/m5stack/hardware/esp32/1.0.7/tools/sdk/include/driver/driver/gpio.h:559:11: note:   initializing argument 1 of 'esp_err_t gpio_hold_en(gpio_num_t)'
 esp_err_t gpio_hold_en(gpio_num_t gpio_num);
           ^
Multiple libraries were found for "SD.h"
 Used: /Users/xxx/Library/Arduino15/packages/m5stack/hardware/esp32/1.0.7/libraries/SD
 Not used: /private/var/folders/64/jgh792qd1fv0081m79s4p8fr0000gn/T/AppTranslocation/3BC7E428-8E20-4BCC-B1DC-862A2D1C7A4B/d/Arduino.app/Contents/Java/libraries/SD
Multiple libraries were found for "WiFi.h"
 Used: /Users/xxx/Library/Arduino15/packages/m5stack/hardware/esp32/1.0.7/libraries/WiFi
 Not used: /private/var/folders/64/jgh792qd1fv0081m79s4p8fr0000gn/T/AppTranslocation/3BC7E428-8E20-4BCC-B1DC-862A2D1C7A4B/d/Arduino.app/Contents/Java/libraries/WiFi
exit status 1
invalid conversion from 'int' to 'gpio_num_t' [-fpermissive]`

**Comment by felmue** [comment]
Hello @openmotion 

glad to hear it worked - thank you for reporting back.

Enjoy your M5Paper!

Cheers
Felix

**Comment by openmotion** [comment]
it worked !
