### ISSUE TITLE
Cannot compile M5stack sample code 

### ISSUE THREAD

**Issue by yutakau** [m5stack/M5Stack#240]
Hi all,

After installing the M5Stack library from scratch, the sample code, "FactoryTest" cannot be compiled due to the following reasons.
The 'WiFi' is not declared anywhere.

Yutaka

C:\Users\yutak\Documents\Arduino\libraries\M5Stack\src\M5Display.cpp: In member function 'void M5Display::drawPngUrl(const char*, uint16_t, uint16_t, uint16_t, uint16_t, uint16_t, uint16_t, double, uint8_t)':

C:\Users\yutak\Documents\Arduino\libraries\M5Stack\src\M5Display.cpp:545:7: error: 'WiFi' was not declared in this scope

**Comment by Gitshaoxiang** [comment]
did you install the esp32 board？ refer to this tutorial to setting.

https://docs.m5stack.com/#/en/arduino/arduino_development
