### ISSUE TITLE
M5Stack.h is messing with WiFiServer

### ISSUE THREAD

**Issue by peopledrivemecrazy** [m5stack/M5Stack#245]
The title!

Unable to use LCD while using m5stack as a HTTP server.

**Comment by Tinyu-Zhao** [comment]
You can see that [WIFI](https://github.com/m5stack/M5Stack/tree/master/examples/Advanced/WIFI)

**Comment by peopledrivemecrazy** [comment]
Can you give me some explanation, please?

**Comment by Tinyu-Zhao** [comment]
> Can you give me some explanation, please?

Can I see your code where the exception occurs

**Comment by Tinyu-Zhao** [comment]
The question is too old and I will close it, if you have any other questions feel free to ask.
