### ISSUE TITLE
Unable to build Factory Test.

### ISSUE THREAD

**Issue by g0lgs** [m5stack/M5Stack#257]
If I try to build the Factory Test code (Arduino IDE 1.8.15 on Pi4B 32bit or Windows 10 64bit ) I get:

sketch/FactoryTest.ino.cpp.o:(.literal._Z11startupLogov+0x0): undefined reference to `m5stack_startup_music'

sketch/FactoryTest.ino.cpp.o:(.literal._Z11startupLogov+0x8): undefined reference to `gImage_logoM5'

At least some of the other examples build fine.

**Comment by Tinyu-Zhao** [comment]
Try putting both files in the same path as factorytest.ino
[bmp_map.c](https://github.com/Tinyu-Zhao/M5Stack/blob/master/examples/Basics/FactoryTest/bmp_map.c)
[startup_music.c](https://github.com/Tinyu-Zhao/M5Stack/blob/master/examples/Basics/FactoryTest/startup_music.c)
like this .
<img width="290" alt="image" src="https://user-images.githubusercontent.com/44396641/129500581-c79c5a40-b1b6-4139-9650-d128423ceb6a.png">

**Comment by g0lgs** [comment]
That sorted it - Thanks.
