### ISSUE TITLE
Code and commit quality

### ISSUE THREAD

**Issue by f4grx** [m5stack/M5Stack#261]
Hello,
can you please have more precisions in your commits?

It is extremely hard to get a sense of what you're doing with that kind of commit:

https://github.com/m5stack/M5Stack/pull/260/commits/b71461937823f1fecaa799ad8bd37b3ef962b434

comment is just "a" 

This is not a good coding practice.

Thank you.

**Comment by Tinyu-Zhao** [comment]
I'll write it in more detail
