### ISSUE TITLE
MPU-6886 Incorrect I2C register set- may be harmless

### ISSUE THREAD

**Issue by ed-french** [m5stack/M5Stack#262]
The driver has been handy thanks!
In making some changes for my particular application I noticed something odd with a register set.
Is it intentional, or was something else intended?

In MPU6886.cpp register  MPU6886_INT_PIN_CFG (0x37) is set to 0x22.
So setting to 1 the bit1 position. 

However the datasheet https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/docs/datasheet/core/MPU-6886-000193%2Bv1.1_GHIC_en.pdf
suggests the bottom bits are Reserved.

What was intended?

Thanks again.

**Comment by Tinyu-Zhao** [comment]
There may be some bugs, I will fix it, thank you.
