### ISSUE TITLE
I want you to register with the library manager. 

### ISSUE THREAD

**Issue by tanakamasayuki** [m5stack/M5Stack#274]
Unregistered library.
I want you to register with the library manager.

The following is probably registerable.

https://github.com/m5stack/ATOM-ECHO
https://github.com/m5stack/CBACK_NBIoT
https://github.com/m5stack/M5-StickT
https://github.com/m5stack/M5Bala
https://github.com/m5stack/M5Tough
https://github.com/m5stack/M5_JoyC
https://github.com/m5stack/M5_RoverC
https://github.com/m5stack/M5_SIM7080G
https://github.com/m5stack/MODULE_DIRECT_STEPMOTOR
https://github.com/m5stack/UNIT_MQTT
https://github.com/m5stack/UNIT_UHF_RFID

## Registration location
https://github.com/arduino/library-registry

**Comment by Tinyu-Zhao** [comment]
Thank you for your kindness, but some of our libraries are still in a state of improvement, and will be released as soon as we improve them.

**Comment by tanakamasayuki** [comment]
Thank you
