### ISSUE TITLE
Conflicts in quaternionFilters.cpp C++17 or later

### ISSUE THREAD

**Issue by GOB52** [m5stack/M5Stack#278]
PlatformIO

I tried compile with -std=gnu++17.

.pio/libdeps/test_17/M5Stack/src/utility/quaternionFilters.cpp:35:14: error: 'float beta' conflicts with a previous declaration
 static float beta = sqrt(3.0f / 4.0f) * GyroMeasError;   // Compute beta

I think, static float beta and std::beta conflicts happend.
see also https://en.cppreference.com/w/cpp/numeric/special_functions/beta

Even if C++17 or later is not currently supported, I think it will be a problem in the future.
I would like to see a fix, either rename the variable or use the appropriate one.

**Comment by Tinyu-Zhao** [comment]
Thank you for your feedback, we have solved the problem
