### ISSUE TITLE
BMP to Array 

### ISSUE THREAD

**Issue by alanroche2015** [m5stack/M5Stack#28]
Hi 

Does anyone have documentation on how to convert a BMP to an array that works with the M5Stack ? I have tried a few methods but without success.

Thanks

**Comment by vvs551** [comment]
Hi,
I usually do it with http://www.riuson.com/lcd-image-converter
You should save bmp in 8-bit format for use it with converter

**Comment by Yazzcat** [comment]
I'm looking for the same possibility to convert an image.

I'v tried your tool, but have no clue what settings for image conversion I need... I can get it to compile, but it only shows garbage on the screen, whatever I try ;-)

**Comment by Yazzcat** [comment]
Ah. Got it! Use the following settings:
Preset: R5G6B5
Block size: 16bit
Byte order: Big-Endian
Leave the rest as it is.

You will need to delete the 'Static' from the .c file and make the array externally available using the extern statement in your code.

Works beautifully!

**Comment by Zontex** [comment]
Glad the problem got solved :) closing the issue.
