### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by henkbb36org** [m5stack/M5Stack#281]
This sketch doesn't work unless I comment out line 48 Serial.begin(115200);

**Comment by Tinyu-Zhao** [comment]
In which example does it appear?

**Comment by henkbb36org** [comment]
This example for gesture recognition:
https://github.com/m5stack/M5Stack/blob/master/examples/Unit/GESTURE_PAJ7620U2/GESTURE_PAJ7620U2.ino

**Comment by Tinyu-Zhao** [comment]
Sorry for the late reply, I've just updated the example, please try again.https://github.com/m5stack/M5Stack/commit/1767c559fdd4fc094cb289a31153ba486f9ac4e5
