### ISSUE TITLE
ESP-IDF Include M5Stack compile failed.

### ISSUE THREAD

**Issue by hequnmin** [m5stack/M5Stack#283]
Compiling .pio\build\m5stack-core-esp32\src\main.cpp.o
Generating partitions .pio\build\m5stack-core-esp32\partitions.bin
Compiling .pio\build\m5stack-core-esp32\lib9e2\M5Stack\Fonts\Font16.c.o
Compiling .pio\build\m5stack-core-esp32\lib9e2\M5Stack\Fonts\Font32rle.c.o
Compiling .pio\build\m5stack-core-esp32\lib9e2\M5Stack\Fonts\Font64rle.c.o
Compiling .pio\build\m5stack-core-esp32\lib9e2\M5Stack\Fonts\Font72rle.c.o
Compiling .pio\build\m5stack-core-esp32\lib9e2\M5Stack\Fonts\Font7srle.c.o
Compiling .pio\build\m5stack-core-esp32\lib9e2\M5Stack\Fonts\glcdfont.c.o
Compiling .pio\build\m5stack-core-esp32\lib9e2\M5Stack\LoRaWan.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib9e2\M5Stack\M5Display.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib9e2\M5Stack\M5Faces.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib9e2\M5Stack\M5LoRa.cpp.o
In file included from .pio\libdeps\m5stack-core-esp32\M5Stack\src\M5Display.cpp:1:0:
.pio\libdeps\m5stack-core-esp32\M5Stack\src\M5Display.h:5:18: fatal error: FS.h: No such file or directory

**Comment by Tinyu-Zhao** [comment]
You can use the repository [M5Unified](https://github.com/m5stack/M5Unified), which supports ESP-IDF.
