### ISSUE TITLE
M5Display Serial message

### ISSUE THREAD

**Issue by mrbanana3000** [m5stack/M5Stack#284]
Feature Request: 

Give an option to disable M5Display "Loaded in X ms" serial message.

Bad for debugging other stuff.

**Comment by Tinyu-Zhao** [comment]
We are sorry for your trouble, you can try commenting out these lines of [code](https://github.com/m5stack/M5Stack/blob/a86173ae032477453fadb9659eb29b75d4da0694/src/ M5Display.cpp#L175-L176) in the native library to solve the problem
