### ISSUE TITLE
version 0.4.0 isn't visible in Arduino library manager

### ISSUE THREAD

**Issue by belm0** [m5stack/M5Stack#285]
Was version 0.4.0 published correctly? Version 0.3.9 is the latest available from the library manager.

![Screen Shot 2022-03-13 at 5 28 07 PM](https://user-images.githubusercontent.com/1708631/158051527-526a1bf5-3d9a-4d1b-9608-579a723558d5.png)

**Comment by Tinyu-Zhao** [comment]
Sorry, we have solved this problem, just wait for the push from Arduino, thanks for your feedback!
