### ISSUE TITLE
4-RELAY... how should be the byte sequence?

### ISSUE THREAD

**Issue by JORGEGO** [m5stack/M5Stack#288]
Dear I am trying to programing 4-Relay with Atom Lite using nanoFramework.

I know that you are not familiar with nanoFramework, but, let me ask about what should be the byte sentence.

I meant I would like for example on relay number 2 (switch on the led and pass the power, close de power, off the led) simple.

I connect the 4-Relay to the AtomLite G26 and G32

I setup the I2C base on nanoFramework address 0x26

And after:
1-  _I2cDevice.WriteByte(0x10); 
2- _I2cDevice.WriteByte(0b0000_0001);  
3- _I2cDevice.WriteByte(0x11);
4- _I2cDevice.WriteByte(0b0100_0100);

And nothing not works...

What should be the list of bytes to send to the relay?

Thanks

**Comment by Tinyu-Zhao** [comment]
You can try this new version of the 4realy [repository](https://github.com/m5stack/UNIT_4RELAY)
