### ISSUE TITLE
Multiple TOF Sensors: I2C Address change

### ISSUE THREAD

**Issue by mazcoder** [m5stack/M5Stack#291]
Not sure if this is the correct venue to ask this question but it appears the community.m5stack.com site is down (where a [similar ](https://community.m5stack.com/topic/2574/how-to-change-the-i2c-adress-of-a-module)question to this has been asked but I cant view the conversation).

I am looking to connect many Time of Flight sensors (VL53L0X SKU: U010) to one controller. Obviously i would need to change addresses from the 0x29 default to something else. Very new to M5Stack but long time Arduino user so apologies if this is called out in the documentation somewhere, but I have not been able to find it.

Is this possible or will I need to DIY an I2C multiplexer?  Thanks in advance

**Comment by Tinyu-Zhao** [comment]
Access to our [forum](https://community.m5stack.com/) is currently normal. You can try another network environment or device to visit.
If you need to reuse multiple devices with the same I2C address, you can try our [PaHub2 Unit](https://docs.m5stack.com/en/unit/pahub2).
