### ISSUE TITLE
M5.Power.isCharging() return false when Battery module attached 

### ISSUE THREAD

**Issue by christophepersoz** [m5stack/M5Stack#294]
### Describe the bug

If you are connecting the Battery Module underneath the M5Stack and then you plug USB-C cable onto a power charger, Power.isCharging() function still return false while it should return true.

### To reproduce

Latest M5-Stack library version under Arduino Framework.

### Expected behavior

Return true as soon as connecting to a power source whether a battery module is attached or not

### Environment

- OS: Mac OS 10.15.7
- IDE &IDE Version: Arduino IDE 1.8.13
- Repository Version: 0.4.3

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Stack/issues?q=)
- [X] My report contains all necessary details

**Comment by Tinyu-Zhao** [comment]
Do you initialize the power module before calling M5.Power.isCharging()?
 M5.Power.begin(); // Init Power module.

I tested it with no problem.
![IMG_6059](https://github.com/m5stack/M5Stack/assets/44396641/7c84a556-6269-46ee-b6ea-f1eb51e5084a)
