### ISSUE TITLE
Working with the painlessMesh library causes an error.

### ISSUE THREAD

**Issue by jonkiszp** [m5stack/M5Stack#297]
### Describe the bug

When I try to use these two libraries in one project I get an error.

https://gitlab.com/painlessMesh/painlessMesh

### To reproduce

code:
`#include <SPI.h>
#include <M5Stack.h>

void setup() {
  Serial.begin(500000);
  M5.begin(true, true, false, true);
  M5.Lcd.fillScreen(BLACK);
  // put your setup code here, to run once:
}

void loop() {
  // put your main code here, to run repeatedly:
  M5.Lcd.setCursor(10,10);
  if (M5.Power.canControl()) {
    M5.Lcd.print(M5.Power.getBatteryLevel());
  } else {
    M5.Lcd.print("Can't control!");
  }
  delay(5000);
}`

ini
`[env:m5stack-core-esp32]
platform = espressif32
board = m5stack-core-esp32
framework = arduino
lib_deps = 
	m5stack/M5Stack@^0.4.3
	painlessmesh/painlessMesh@^1.5.0
monitor_speed = 500000`

and build in Platformio 6.1.5

### Expected behavior

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/m5stack-core-esp32.html
PLATFORM: Espressif 32 (5.2.0) > M5Stack Core ESP32
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 @ 3.20005.220925 (2.0.5)
 - tool-esptoolpy @ 1.40201.0 (4.2.1)
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 37 compatible libraries
Scanning dependencies...
Dependency Graph
|-- M5Stack @ 0.4.3
|   |-- FS @ 2.0.0
|   |-- HTTPClient @ 2.0.0
|   |   |-- WiFi @ 2.0.0
|   |   |-- WiFiClientSecure @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |-- SD @ 2.0.0
|   |   |-- FS @ 2.0.0
|   |   |-- SPI @ 2.0.0
|   |-- SPI @ 2.0.0
|   |-- Wire @ 2.0.0
|   |-- SPIFFS @ 2.0.0
|   |   |-- FS @ 2.0.0
|-- painlessMesh @ 1.5.0
|   |-- ArduinoJson @ 6.19.4
|   |-- TaskScheduler @ 3.7.0
|   |-- AsyncTCP @ 1.1.1
|   |-- WiFi @ 2.0.0
|   |-- SPIFFS @ 2.0.0
|   |   |-- FS @ 2.0.0
|-- SPI @ 2.0.0
Building in release mode
Compiling .pio\build\m5stack-core-esp32\src\main.cpp.o
Building .pio\build\m5stack-core-esp32\bootloader.bin
Generating partitions .pio\build\m5stack-core-esp32\partitions.bin
esptool.py v4.2.1
Creating esp32 image...
Merged 1 ELF section
Successfully created esp32 image.
Compiling .pio\build\m5stack-core-esp32\lib0cf\FS\FS.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib0cf\FS\vfs_api.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib42c\WiFi\WiFi.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib42c\WiFi\WiFiAP.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib42c\WiFi\WiFiClient.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib42c\WiFi\WiFiGeneric.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib42c\WiFi\WiFiMulti.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib42c\WiFi\WiFiSTA.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib42c\WiFi\WiFiScan.cpp.o
Archiving .pio\build\m5stack-core-esp32\lib0cf\libFS.a
Compiling .pio\build\m5stack-core-esp32\lib42c\WiFi\WiFiServer.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib42c\WiFi\WiFiUdp.cpp.o
Compiling .pio\build\m5stack-core-esp32\libb24\WiFiClientSecure\WiFiClientSecure.cpp.o
Compiling .pio\build\m5stack-core-esp32\libb24\WiFiClientSecure\esp_crt_bundle.c.o
Compiling .pio\build\m5stack-core-esp32\libb24\WiFiClientSecure\ssl_client.cpp.o
Compiling .pio\build\m5stack-core-esp32\libdac\HTTPClient\HTTPClient.cpp.o
Archiving .pio\build\m5stack-core-esp32\lib42c\libWiFi.a
Compiling .pio\build\m5stack-core-esp32\lib055\SPI\SPI.cpp.o
Compiling .pio\build\m5stack-core-esp32\libe43\SD\SD.cpp.o
Compiling .pio\build\m5stack-core-esp32\libe43\SD\sd_diskio.cpp.o
Compiling .pio\build\m5stack-core-esp32\libe43\SD\sd_diskio_crc.c.o
Archiving .pio\build\m5stack-core-esp32\lib055\libSPI.a
Compiling .pio\build\m5stack-core-esp32\lib373\Wire\Wire.cpp.o
Archiving .pio\build\m5stack-core-esp32\libb24\libWiFiClientSecure.a
Compiling .pio\build\m5stack-core-esp32\lib18f\SPIFFS\SPIFFS.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\Fonts\Font16.c.o
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\Fonts\Font32rle.c.o
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\Fonts\Font64rle.c.o
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\Fonts\Font72rle.c.o
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\Fonts\Font7srle.c.o
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\Fonts\glcdfont.c.o
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\IMU.cpp.o
Archiving .pio\build\m5stack-core-esp32\libe43\libSD.a
Archiving .pio\build\m5stack-core-esp32\libdac\libHTTPClient.a
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\LoRaWan.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\M5Display.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\M5Faces.cpp.o
Archiving .pio\build\m5stack-core-esp32\lib373\libWire.a
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\M5LoRa.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\M5Stack.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\utility\Button.cpp.o
Archiving .pio\build\m5stack-core-esp32\lib18f\libSPIFFS.a
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\utility\CommUtil.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\utility\In_eSPI.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\utility\M5Timer.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\utility\MPU6886.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\utility\MPU9250.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\utility\MahonyAHRS.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\utility\Power.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\utility\SH200Q.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\utility\Speaker.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\utility\Sprite.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\utility\pngle.c.o
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\utility\qrcode.c.o
Compiling .pio\build\m5stack-core-esp32\lib776\M5Stack\utility\quaternionFilters.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib4c8\AsyncTCP\AsyncTCP.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib3f6\painlessMesh\painlessMeshSTA.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib3f6\painlessMesh\scheduler.cpp.o
Compiling .pio\build\m5stack-core-esp32\lib3f6\painlessMesh\wifi.cpp.o
Compiling .pio\build\m5stack-core-esp32\FrameworkArduino\Esp.cpp.o
Compiling .pio\build\m5stack-core-esp32\FrameworkArduino\FirmwareMSC.cpp.o
Compiling .pio\build\m5stack-core-esp32\FrameworkArduino\FunctionalInterrupt.cpp.o
Archiving .pio\build\m5stack-core-esp32\lib776\libM5Stack.a
Compiling .pio\build\m5stack-core-esp32\FrameworkArduino\HWCDC.cpp.o
Archiving .pio\build\m5stack-core-esp32\lib4c8\libAsyncTCP.a
Compiling .pio\build\m5stack-core-esp32\FrameworkArduino\HardwareSerial.cpp.o
Compiling .pio\build\m5stack-core-esp32\FrameworkArduino\IPAddress.cpp.o
Compiling .pio\build\m5stack-core-esp32\FrameworkArduino\IPv6Address.cpp.o
In file included from .pio/libdeps/m5stack-core-esp32/painlessMesh/src/painlessmesh/mesh.hpp:12,
                 from .pio/libdeps/m5stack-core-esp32/painlessMesh/src/painlessMeshSTA.h:6,
                 from .pio/libdeps/m5stack-core-esp32/painlessMesh/src/arduino/wifi.hpp:8,
                 from .pio/libdeps/m5stack-core-esp32/painlessMesh/src/painlessMeshSTA.cpp:16:
.pio/libdeps/m5stack-core-esp32/painlessMesh/src/painlessmesh/ota.hpp:13:10: fatal error: Update.h: No such file or directory

****************************************************************
* Looking for Update.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Update.h"
* Web  > https://registry.platformio.org/search?q=header:Update.h
*
****************************************************************

 #include <Update.h>
          ^~~~~~~~~~
compilation terminated.
*** [.pio\build\m5stack-core-esp32\lib3f6\painlessMesh\painlessMeshSTA.cpp.o] Error 1
In file included from .pio/libdeps/m5stack-core-esp32/painlessMesh/src/painlessmesh/mesh.hpp:12,
                 from .pio/libdeps/m5stack-core-esp32/painlessMesh/src/painlessMeshSTA.h:6,
                 from .pio/libdeps/m5stack-core-esp32/painlessMesh/src/arduino/wifi.hpp:8,
                 from .pio/libdeps/m5stack-core-esp32/painlessMesh/src/wifi.cpp:1:
.pio/libdeps/m5stack-core-esp32/painlessMesh/src/painlessmesh/ota.hpp:13:10: fatal error: Update.h: No such file or directory

****************************************************************
* Looking for Update.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Update.h"
* Web  > https://registry.platformio.org/search?q=header:Update.h
*
****************************************************************

 #include <Update.h>
          ^~~~~~~~~~
compilation terminated.
*** [.pio\build\m5stack-core-esp32\lib3f6\painlessMesh\wifi.cpp.o] Error 1

### Environment

- OS: Windows 11
- IDE &IDE Version: Platformio 6.1.5

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Stack/issues?q=)
- [X] My report contains all necessary details

**Comment by Tinyu-Zhao** [comment]
Use this code and it will compile
```cpp
#include <M5Stack.h>
#include <SPI.h>
#include <Update.h>

void setup() {
    Serial.begin(500000);
    M5.begin(true, true, false, true);
    M5.Lcd.fillScreen(BLACK);
    // put your setup code here, to run once:
}

void loop() {
    // put your main code here, to run repeatedly:
    M5.Lcd.setCursor(10, 10);
    if (M5.Power.canControl()) {
        M5.Lcd.print(M5.Power.getBatteryLevel());
    } else {
        M5.Lcd.print("Can't control!");
    }
    delay(5000);
}
```
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/44396641/216831645-ee98ca0d-20b7-46c4-aae3-bc3657f6af50.png">
