### ISSUE TITLE
Hardware reset error

### ISSUE THREAD

**Issue by DeltaCore** [m5stack/M5Stack#30]
I have noticed an error in the current schematic.

At the transistor VT3: Collector and Emitter are switched.
<img width="777" alt="mark1" src="https://user-images.githubusercontent.com/5575913/33425929-7f14e44e-d5c0-11e7-8fbf-a3e05f845185.png">

This error prevents the usb reset circuit to work properly.

An easy workaround was to manually bridge GPIO0 and GND to flash a OTA firmware.

Best regards
 - Marcel / deltacore

**Comment by MarsTechHAN** [comment]
Sorry for misleading, we notice the schematics we put on were a very old version. We will replace it as soon as possible. 
This image is from the PCB file that we send to manufaturing. 
![image](https://user-images.githubusercontent.com/10462805/33696753-b523906a-dad1-11e7-8ffb-258fe528c847.png)
And the new version of pdf.
![image](https://user-images.githubusercontent.com/10462805/33696760-c0e1ab8a-dad1-11e7-95de-a1eeb53b888a.png)

**Comment by DeltaCore** [comment]
This was my solution :P

![img_0619](https://user-images.githubusercontent.com/5575913/33770487-0384ec9c-dc2e-11e7-8fcb-1479d9463fe3.JPG)

I turned the transistor on it's head and rotated it so the emitter and collector are switched.

Best regards
 - Marcel

**Comment by DeltaCore** [comment]
To be clear, i was not able to program the m5stack without the soldering i did my self.
I will probe the connections on my board to check if i have the board you attached a picture of or a different one.

Best regards
 - Marcel
