### ISSUE TITLE
Broken Boards Manager Link

### ISSUE THREAD

**Issue by kjjohnsen** [m5stack/M5Stack#300]
### Describe the bug

https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/arduino/package_m5stack_index.json is currently blank, meaning it is not possible to install the m5stack boards into Arduino by following the official instructions.  This link was working a few days ago. 

### To reproduce

Click https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/arduino/package_m5stack_index.json (currently blank, as of now)

### Expected behavior

A boards json would be downloaded

### Environment

- OS:
- IDE &IDE Version:
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Stack/issues?q=)
- [X] My report contains all necessary details

**Comment by Tinyu-Zhao** [comment]
Just getting ready for update 2.0.6 and it's back to normal now, thank you.
