### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by alanroche2015** [m5stack/M5Stack#31]
M5,

Can we create a gitter community ?

**Comment by m5stack** [comment]
surely i wish to.

**Comment by alanroche2015** [comment]
Great I think the admin needs to create the gitter account.

**Comment by tobozo** [comment]
@m5stack please log into gitter.im using your github account and create the room https://gitter.im/m5stack/m5stack

**Comment by tobozo** [comment]
https://gitter.im/M5STACK_FANS/Lobby
