### ISSUE TITLE
M5Stack Library won't install on Arduino IDE

### ISSUE THREAD

**Issue by JaimeCababie** [m5stack/M5Stack#314]
### Describe the bug

M5 Stack library 0.4.5 wont install when using the library manager because 'MODULE_GRBL13.2' is not available. 

### To reproduce

1. open library manager
2. search for M5Stack Library 
3. Try to install M5Stack v. 0.4.5 

### Expected behavior

I would expect for the library to install

### Screenshots

![image](https://github.com/m5stack/M5Stack/assets/98760075/1f8634d7-44fd-45c1-8397-cdf6f6c64c04)

### Environment

Arduino IDE 2.2.1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Stack/issues?q=)
- [X] My report contains all necessary details

**Comment by srolf** [comment]
Same for me, any version of "M5Stack" library 0.4.1 is causing such a dependency problem.

**Comment by CitrusPeel** [comment]
The package's name "MODULE_GRBL13.2" in [library.properties](https://github.com/m5stack/M5Stack/blob/master/library.properties) should be "MODULE_GRBL_13.2"

**Comment by sigmaeo** [comment]
this is fixed in M5StackCore2 0.1.7
