### ISSUE TITLE
Failed to install library: 'M5Core2:0.1.6'. No valid dependencies solution found: dependency 'MODULE_GRBL13.2' is not available

### ISSUE THREAD

**Issue by BFang-Overflow** [m5stack/M5Stack#315]
### Describe the bug

Failed to install library: 'M5Core2:0.1.6'. No valid dependencies solution found: dependency 'MODULE_GRBL13.2' is not available
When try to install ```M5Core2``` from arduino lib

### To reproduce

Arduino IDE windows 2.2.1
![2023_09_13_12_222337d](https://github.com/m5stack/M5Stack/assets/117389508/15e7077c-f8ac-4c2b-b638-fb7d03cf66b6)

### Expected behavior

![2023_09_13_12_222337d](https://github.com/m5stack/M5Stack/assets/117389508/501bd300-8622-4001-a67d-8538754651da)

### Screenshots

![2023_09_13_12_222337d](https://github.com/m5stack/M5Stack/assets/117389508/345e8b0f-d3fd-4e0f-b8bc-dfb4f9634f25)

### Environment

- OS:
- IDE &IDE Version:
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Stack/issues?q=)
- [X] My report contains all necessary details

**Comment by sigmaeo** [comment]
this is fixed in M5StackCore2 0.1.7
