### ISSUE TITLE
M5Stack library isn't compatible with M5Stack CoreS3

### ISSUE THREAD

**Issue by DenDonnar** [m5stack/M5Stack#316]
### Describe the bug

I wanted to just display simple "Hello, World" on a M5Stack CoreS3, but I've got that error msg:

In file included from c:\Arduino\libraries\M5Stack\src/M5Display.h:8,
                 from c:\Arduino\libraries\M5Stack\src/M5Stack.h:111,
                 from C:\Arduino\sketch_oct25a\sketch_oct25a.ino:1:
c:\Arduino\libraries\M5Stack\src/utility/In_eSPI.h:633:20: error: 'VSPI' was not declared in this scope
     uint8_t port = VSPI;
                    ^~~~
c:\Arduino\libraries\M5Stack\src/utility/In_eSPI.h:633:20: note: suggested alternative: 'SPI'
     uint8_t port = VSPI;
                    ^~~~
                    SPI
                    

### To reproduce

1 Arduino IDE (with M5Stack.h installed)
2 Connect M5Stack CoreS3
3 Try tu upload that simple code:

#include <M5Stack.h>

void setup() {
  M5.begin();
  M5.Lcd.fillScreen(BLACK);
  M5.Lcd.setTextColor(WHITE, BLACK);  
  M5.Lcd.setTextSize(2);
  M5.Lcd.setCursor(0, 0);
  M5.Lcd.print("Hello, World!");
}

void loop() {
 
}

### Expected behavior

To see "Hello, World!" on my M5StackCoreS3 Screen

### Environment

- OS: Windows 10 also tried on Ubuntu 22.04
- IDE &IDE Version: Arduino IDE 2.2.1
- Repository Version: 0.4.6 (the newest one)

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Stack/issues?q=)
- [X] My report contains all necessary details

**Comment by felmue** [comment]
Hello @DenDonnar 

there is a separate library for M5CoreS3. Please see [here](https://github.com/m5stack/M5CoreS3).

Thanks
Felix
