### ISSUE TITLE
Platformio gives an error when compiling

### ISSUE THREAD

**Issue by blynkkk** [m5stack/M5Stack#32]
When compiling Blynk example: 
```
/src/Blynk/BlynkTimer.h:38:36: error: conflicting declaration 'typedef
 void (* timer_callback)()'
```

Seems that you are including your own version of Timer and it's conflicting with the one included in the Blynk lib

**Comment by kuboken55** [comment]
Rewrite the header file M5Timer.h as follows.

> //typedef std::function<void(void)> timer_callback;
> typedef void (*timer_callback)(void);
> typedef void (*timer_callback_p)(void *);

**Comment by Zontex** [comment]
Seems like you got an answer with solution, hope it helped! closing for now.
