### ISSUE TITLE
please What is the meaning of this? How can it be solved?

### ISSUE THREAD

**Issue by mostafanafie5** [m5stack/M5Stack#323]
### Describe the bug

please What is the meaning of this? How can it be solved?

### To reproduce

please What is the meaning of this? How can it be solved?

### Expected behavior

please What is the meaning of this? How can it be solved?

### Screenshots

![IMG_20240222_021605](https://github.com/m5stack/M5Stack/assets/97190483/74a7fa16-d502-4a1c-9574-8dcf346ebbbe)

### Environment

- OS:
- IDE &IDE Version:
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Stack/issues?q=)
- [X] My report contains all necessary details

**Comment by Tinyu-Zhao** [comment]
Please attach your program, without providing more details, it is impossible to troubleshoot.

**Comment by Tinyu-Zhao** [comment]
The questioner cannot provide useful information, so it is closed.
