### ISSUE TITLE
TFT_Meter_linear.ino & TFT_Meters.ino does not compile

### ISSUE THREAD

**Issue by versamodule** [m5stack/M5Stack#38]
Compiling .pioenvs\m5stack-core-esp32\src\main.o
<command-line>:0:16: warning: ISO C++11 requires whitespace after the macro name
src\main.cpp: In function 'void setup()':
src\main.cpp:36:15: error: 'analogMeter' was not declared in this scope
analogMeter(); // Draw analogue meter

**Comment by 0x1abin** [comment]
Thank you very much for your feedback, I have fixed the compilation error :)
