### ISSUE TITLE
led matrix stack

### ISSUE THREAD

**Issue by machinehistories** [m5stack/M5Stack#43]
Not sure where to ask about this but is the led matrix stack available for sale. If not are the components documented and is there any info on putting it together.

**Comment by jimitortuga** [comment]
Hi,
Product questions like this are probs best raised in the M5 user forum....  http://forum.m5stack.com/

I haven't seen the LED Matrix module offered for sale or heard any mentions that it is upcoming.... whereas other modules  have been mentioned.  So they may not have mentioned it or it may be planned for release later... not sure.

**Comment by Zontex** [comment]
Not an issue, can be asked over forum.m5stack.com for best response.
