### ISSUE TITLE
pushRect in Display.cpp is broken

### ISSUE THREAD

**Issue by richi** [m5stack/M5Stack#48]
Hi,
The M5Stack display and the ESP32 have different byte orders but pushRect()  in Display.cpp assumes the same byte order on MCU and display. It does use writeBytes() to send uint16_t values and therefore causes colourful but wrong results...

The following code starting at line 1590 in Display.cpp

```
  uint32_t len = w * h * 2;
  // Push pixels into window rectangle, data is a 16 bit pointer thus increment
  // is halved
  while (len >= 32) {
    SPI.writeBytes((uint8_t *)data, 32);
    data += 16;
    len -= 32;
  }
  if (len)
    SPI.writeBytes((uint8_t *)data, len);

```

should be replaced with

```
  uint32_t len = w * h;
  for(uint16_t i=0; i<len; i++) {
    SPI.write16(data[i]);
  }

```

**Comment by Zontex** [comment]
Hello, is this problem still persist? you can send pull requests for modifications if required, we will look over it. closed for now.
