### ISSUE TITLE
LCD.Invert or similar?

### ISSUE THREAD

**Issue by Eina61** [m5stack/M5Stack#50]
Is there any way to invert the entire LCD display? I need to have the USB cable on the right side and then display will be upside down.

**Comment by tobozo** [comment]
Have you tried the different values of `M5.Lcd.setRotation()` ? 

https://github.com/m5stack/M5Stack/blob/master/src/utility/Display.h#L485

**Comment by Eina61** [comment]
Oh, thanks very much!

I looked in the API documentation here:
https://github.com/m5stack/M5Stack/blob/master/src/M5Stack.h#L19
and couldn't find anything.

M5.lcd.setRotation(2);
rotates the display 180 degrees.
