### ISSUE TITLE
time to upgrade Display.cpp to the latest version of TFT_eSPI

### ISSUE THREAD

**Issue by laurentopia** [m5stack/M5Stack#54]
dontcha think?
I tried to do that but there are too many things flying everywhere, so instead I docked m5stack lib and use eSPI instead. A shame that most m5stack users won't get to enjoy that so someone good does it and push the change por favor.

**Comment by 0x1abin** [comment]
I am sorry too late reply and thanks for your reminder. I will upgrade latest eSPI lib integration version at this week.

**Comment by laurentopia** [comment]
Great news :)
