### ISSUE TITLE
error: no matching function for call to 'M5Display::drawBitmap

### ISSUE THREAD

**Issue by htpbbp** [m5stack/M5Stack#62]
Hi there,

tried the example from ...

http://forum.m5stack.com/topic/143/lesson-6-1-speaker-mp3-player/2

... and got this error:

mp3-player-m5stack:279: error: no matching function for call to 'M5Display::drawBitmap(int, int, int, int, uint16_t*)'
   M5.Lcd.drawBitmap(0, 0, 320, 150, (uint16_t *)logo);

**Comment by tobozo** [comment]
already listed in #61 I hope there'll be a wrapper or an alias soon

**Comment by 0x1abin** [comment]
Sorry, I left out some drawing methods. I have added some compatible wrappers and re-released v0.1.9.

**Comment by tobozo** [comment]
I'll test against the latest git clone as it does not appear to have landed in the release zip file yet
