### ISSUE TITLE
[FEATURE REQUEST] USB connection as USB Mass storage

### ISSUE THREAD

**Issue by marshel** [m5stack/M5Stack#70]
Adafruit has a feature on circuit python where the default firmware on device is recognized as a mass storage device on PC. 

You then may upload .py files that the micro controller can use after a reset or send over serial python commands.

You can also upload other files. (images, assets, game ROMs, videos, mp3.....)

Suggestion, Develop a firmware with this ability or contribute to the circuit python repo so M5stack get supported.

**Comment by marshel** [comment]
Just referencing: https://github.com/adafruit/circuitpython

**Comment by tobozo** [comment]
also [this](https://github.com/tomorrow56/M5Stack_USBHost_PS3BT)

**Comment by Zontex** [comment]
Hello, our eco-system currently is working in different way such as flow.m5stack.com that works with our firmware, implementing the same way Adafruit did will conflict with the UIFlow firmware. but this is definitely an interesting idea and suggestion that we could look into future releases, thank you for the suggestion! Closing this for now.
