### ISSUE TITLE
m5stack_startup_music not defined in Speaker example

### ISSUE THREAD

**Issue by jadr2ddude** [m5stack/M5Stack#73]
It appears that the startup music is in the FactoryTest example and is therefore inaccessible to the Speaker example. This music must be copied to the Speaker example to get this to work.

**Comment by jadr2ddude** [comment]
Appears that issue #69 is similar

**Comment by 0x1abin** [comment]
Thanks for your feedback, is an old way to play music, I remove it, but you can find out this file at [this](https://github.com/m5stack/M5Stack/blob/master/examples/Basics/FactoryTest/startup_music.cl)
If you want play music, reference: https://github.com/m5stack/M5Stack/tree/master/examples/Advanced/Audio

**Comment by tobozo** [comment]
[permalink to 'this'](https://github.com/m5stack/M5Stack/blob/7e863fb9934bcb25f15afa720e9299b8a8e9a8fd/examples/Basics/FactoryTest/startup_music.c)
