### ISSUE TITLE
Some example sketches could not be compiled.

### ISSUE THREAD

**Issue by tchisaka** [m5stack/M5Stack#79]
Some example sketches could not be compiled.

  - M5Stack/examples/Advanced/Display/TFT_Mandlebrot/TFT_Mandlebrot.ino
  - M5Stack/examples/Advanced/Display/TFT_Matrix/TFT_Matrix.ino
  - M5Stack/examples/Advanced/Display/UTFT_demo/UTFT_demo.ino

In these sketches, I could compile with the following modifications.

    randomSeed(analogRead(A0))
    -> randomSeed(analogRead(35))

**Comment by 0x1abin** [comment]
Thank you very much for your feedback, I have fixed the compilation error :)

**Comment by Zontex** [comment]
Compilation fixed, closing the issue.
