### ISSUE TITLE
No display, just a pulsing static noise

### ISSUE THREAD

**Issue by watahboy** [m5stack/M5Stack#82]
I ordered the m5stack as soon as it was available to me and had a sketch showing me BTC prices from an exchange and it worked for about 3 months. Now the m5stack is just making a static/ scratching noise about every half second and otherwise is showing no signs of life. I tried reflashing the sketch and I am getting the same result. Did my unit fry?

**Comment by joeybab3** [comment]
Probably if you're no longer able to upload sketches to it. Try reaching out to the site where you bought it from.

**Comment by sulolullero** [comment]
Hi @watahboy! Did you resolve the issue? I'm having same problems currently. Cheers, Mikko

**Comment by cmoncada** [comment]
I have same problem! any fix or clue!!!

**Comment by EeeeBin** [comment]
For some reasons, our BTC price acquisition service has been closed, try find other APIs to get BTC prices

**Comment by cmoncada** [comment]
I Only configured wifi, restarted M5stack, but now is only making noise and screen is off.

**Comment by EeeeBin** [comment]
Could you show the USB UART debug info

**Comment by flouroantimonic-acid** [comment]
I got this same problem, and I just got mine. I can upload and serial works fine. No idea why. I'm kinda pissed.

**Comment by flouroantimonic-acid** [comment]
It seems that the speaker works fine (tested with the Speaker example), but the Display example does nothing.

**Comment by Gitshaoxiang** [comment]
any product questions.  pls contact the our store.  like AliExpress
